language: python
python:
  - "2.7"

install:
  - pip install -r test/travis/test-requirements.txt

script: nosetests test/unit/

branches:
  only:
    - master

notifications:
  email: true

cache:
  apt: true
